service: hello

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: ap-northeast-1
  apiKeys:
    - internal
  iamRoleStatements:
    - Effect: Allow
      Action:
        - "dynamodb:*"
      Resource: "arn:aws:dynamodb:${self:provider.region}:*:table/*"

plugins:
  - serverless-plugin-write-env-vars
  - serverless-webpack

custom:
  webpackIncludeModules: true
  writeEnvVars:
    REGION: ${self:provider.region}

functions:
  hello:
    handler: hello.read
    events:
      - http:
          path: hello
          method: get
          private: true

  getTicket:
    handler: tickets.get
    events:
      - http:
          path: tickets/{ticketKey}
          method: get
          private: true

  putTicket:
    handler: tickets.put
    events:
      - http:
          path: tickets/{ticketKey}
          method: put
          private: true

resources:
  Resources:
    Ticket:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: ticketKey
            AttributeType: S
        KeySchema:
          -
            AttributeName: ticketKey
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: 'Tickets'
