service: hello

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: ap-northeast-1

plugins:
  - serverless-webpack

functions:
  hello:
    handler: hello.read
    events:
       - http:
           path: hello
           method: get
