service: hello

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: ap-northeast-1
  apiKeys:
    - internal

plugins:
  - serverless-webpack

functions:
  hello:
    handler: hello.read
    events:
      - http:
          path: hello
          method: get
          private: true

  getTicket:
    handler: tickets.readOne
    events:
      - http:
          path: tickets/{key}
          method: get
          private: true

  getTickets:
    handler: tickets.read
    events:
      - http:
          path: tickets
          method: get
          private: true
